Add tram stop by stop
wmcadigital/wmn-disruptions pull request #424
Opened 2020-12-07 12:11 UTC by gldgrnt

2020-12-08 14:13 UTC, daylesalmon requested changes
Just  a few changes.

Another bug I have noticed is...

- Fresh start the app
- Click tram
- Select any two stops
- The API fetches the in-between stops
- Whilst this fetching is going on, the spinner shows but also "good service" remains.

Whilst fetching, the good service shouldn't show until the API has resolved.

2020-12-08 14:13 UTC, daylesalmon commented on src/components/shared/Tray/TrayComponents/AutoComplete/TrainAutoComplete/TrainAutocomplete.js
>                placeholder="Search for a stop"
Can we change this to "Search for a station"

2020-12-08 14:13 UTC, daylesalmon commented on src/components/shared/Tray/TrayComponents/SelectedService/InfoAboutSelectedService/TramInfoAboutSelectedService/TramInfoAboutSelectedService.js
> +  const { loading, errorInfo } = useGetTramStopByStop();
To tidy this file a bit more, return the autoCompleteState from the useGetTramStopByStop.

2020-12-08 14:13 UTC, daylesalmon commented on src/components/shared/Tray/TrayComponents/SelectedService/InfoAboutSelectedService/TramInfoAboutSelectedService/customHooks/useGetTramStopByStop.js
> +  // Intitialise state
```suggestion
  // initialise state
```

2020-12-08 14:13 UTC, daylesalmon commented on src/components/shared/Tray/TrayComponents/SelectedService/InfoAboutSelectedService/TramInfoAboutSelectedService/customHooks/useGetTramStopByStop.js
> +  return { loading, errorInfo };
Return the autoCompleteState here so you can just use it in your other file.

2020-12-08 14:13 UTC, daylesalmon commented on src/components/shared/Tray/TrayComponents/SelectedService/InfoAboutSelectedService/helpers/numberToWord.js
> +    'Thirty',
Check all the typos in here. Some "Thirty" are "Thrity".

2020-12-08 14:13 UTC, daylesalmon commented on src/customHooks/useFilterLogic.js
> +            const lineCodes = autoCompleteState.selectedItem.lines.map((stop) => stop.atcoCode);
Lets add "atcoCode" to the typo.yml exclude list.

2020-12-08 15:16 UTC, gldgrnt commented
> Just a few changes.
> 
> Another bug I have noticed is...
> 
> * Fresh start the app
> * Click tram
> * Select any two stops
> * The API fetches the in-between stops
> * Whilst this fetching is going on, the spinner shows but also "good service" remains.
> 
> Whilst fetching, the good service shouldn't show until the API has resolved.

@daylesalmon I'm fixing this in another branch, where I'm also fixing the bug where the 'Good Service' message should show straight away for modes with no disruptions. I'll create a PR once this has been merged 👍🏾

2020-12-09 14:06 UTC, daylesalmon approved these changes
All good!

2020-12-09 14:06 UTC, merged